---
- name: "Desktop | Tmux | Tmuxinator | Show default shell"
  ansible.builtin.debug:
    msg: "Default shell is {{ ansible_env.SHELL }}"

- name: "Desktop | Tmux | Tmuxinator | Check if tmuxinator is installed"
  ansible.builtin.command: "which tmuxinator"
  register: "_desktop_tmux_tmuxinator_check"
  changed_when: false
  failed_when: false

- name: "Desktop | Tmux | Tmuxinator | Display tmuxinator status"
  ansible.builtin.debug:
    msg: "Tmuxinator is already installed"
  when: "_desktop_tmux_tmuxinator_check.rc == 0"

- name: "Desktop | Tmux | Tmuxinator | Install tmuxinator"
  when: "_desktop_tmux_tmuxinator_check.rc != 0"
  block:

    - name: "Desktop | Tmux | Tmuxinator | Display tmuxinator status"
      ansible.builtin.debug:
        msg: "Tmuxinator is not installed, proceeding with installation"
    
    - name: "Desktop | Tmux | Tmuxinator | Install dependencies"
      become: true
      ansible.builtin.package:
        name: "{{ desktop_tmux_tmuxinator_dependencies }}"
        state: present

    - name: "Desktop | Tmux | Tmuxinator | Ruby install gem tmuxinator"
      ansible.builtin.command: >
        gem install tmuxinator
      register: "_desktop_tmux_tmuxinator_install"
      changed_when: true

  rescue:

    - name: "Desktop | Tmux | Tmuxinator | Display error message"
      ansible.builtin.debug:
        msg: "Tmuxinator installation failed. Please check the logs for more details." 

- name: "Desktop | Tmux | Tmuxinator | Set completions for tmuxinator when using fish"
  when: "'fish' in ansible_env.SHELL"
  block:

    - name: "Desktop | Tmux | Ensure fish completions directory exists"
      ansible.builtin.file:
        path: "{{ ansible_env.HOME }}/.config/fish/completions"
        state: "directory"
        mode: "0755"

    - name: "Desktop | Tmux | Download tmuxinator.fish completion script"
      ansible.builtin.get_url:
        url: "https://raw.githubusercontent.com/tmuxinator/tmuxinator/master/completion/tmuxinator.fish"
        dest: "{{ ansible_env.HOME }}/.config/fish/completions/tmuxinator.fish"
        mode: "0644"

- name: "Desktop | Tmux | Tmuxinator | Set completions for tmuxinator when using bash"
  become: true
  when: "'bash' in ansible_env.SHELL"
  block:

    - name: "Desktop | Tmux | Download tmuxinator.bash completion script to bash_completion.d"
      ansible.builtin.get_url:
        url: "https://raw.githubusercontent.com/tmuxinator/tmuxinator/master/completion/tmuxinator.bash"
        dest: "/etc/bash_completion.d/tmuxinator.bash"
        mode: "0644"
        validate_certs: true  # Optional, ensure the server has a valid SSL certificate

- name: "Desktop | Tmux | Tmuxinator | Set completions for tmuxinator when using zsh"
  become: true
  when: "'zsh' in ansible_env.SHELL"
  block:

    - name: Ensure zsh site-functions directory exists
      ansible.builtin.file:
        path: "/usr/local/share/zsh/site-functions"
        state: "directory"
        mode: "0755"

    - name: Download tmuxinator.zsh completion script for Zsh
      ansible.builtin.get_url:
        url: "https://raw.githubusercontent.com/tmuxinator/tmuxinator/master/completion/tmuxinator.zsh"
        dest: "/usr/local/share/zsh/site-functions/_tmuxinator"
        mode: "0644"
        validate_certs: true  # Optional, ensures the server has a valid SSL certificate

...
